### ISSUE TITLE
Comment/Uncomment routines

### ISSUE THREAD

**Issue by areYouLazy** [txn2/txeh#13]
It would be useful for the library to have Comment() and Uncomment() routines to change the LineType of a HostFileLine without actually remove the ip-fqdn reference

**Comment by cjimti** [comment]
'txeh` is built around adding and removing hosts to an IP. Since there is one IP per line it would be ambiguous as to what Comment() and Uncomment() would do, since `/etc/hosts` does not support inline comments.
