### ISSUE TITLE
supoort hosts with duplicate ip for one fqdn

### ISSUE THREAD

**Issue by yeluolei** [txn2/txeh#15]
I know you have removed duplicate address for same fqdn, but if the hosts file is used by dnsmasq, it will need that to implement round robin dns address load balance. so maybe it's a good idea to keep these lines if a parameter is specified.

**Comment by cjimti** [comment]
@yeluolei this is a controversial issue, most systems don't support round robin from /etc/hosts, only DNS, please see:
- https://serverfault.com/questions/429839/assign-multiple-ips-to-1-entry-in-hosts-file

@addshore it does seem like it needs to support duplicates for IPv6, however, I don't fully understand why. Is that used for a reverse lookup? Most systems will see the first IP for localhost and use it.
