### ISSUE TITLE
Feature Request: Include comment during add:  only remove entries matching existing comment

### ISSUE THREAD

**Issue by mattkasun** [txn2/txeh#19]
Feature Request:
1. add ability to add a comment when adding entries e.g.
10.10.10.25 www.example.com #added by programXXX
2. add ability to remove an entry iff the comment matches comment passed as param.

This would enable programs using txeh as a library to limit deletions to only those entries that it had added previously.

I see two options for implementation:

1.  Add a comment param to RemoveAddresses(), RemoveAddress(), RemoveFirstAddress(), RemoveHosts(), RemoveHost(), RemoveFirstHost(), AddHosts(), AddHost() and HostAddressLookup()

2. Add new func for each of the above e.g. RemoveAddressesWithComment(), RemoveAddressWithComment(), etc.

with option 1 the signature of several functions would be changed and thus users of the lib would have to add a blank string as an extra param to the above calls.  also calling a remove func with an empty comment param would not delete matching entries that did contain a comment.

option 2 adds a significant amount of duplicated code but maintains signatures for existing functions so users of the library would not have to update any code that uses the library.

I am willing to submit a PR for either option.

 .

**Comment by cjimti** [comment]
Thanks for your interest in `txeh`. Sorry, it has taken me so long to look at this issue.

If you add a host to an existing IP in the file, you can't claim ownership of the line/IP. Keep in mind that there should only be one line per IP. see: https://lists.debian.org/debian-devel/2004/06/msg00468.html 

If `txeh` opens a new `/etc/hosts` and adds a new IP with one or more hosts and another system or user manually added a host to that line, it's not technically safe unless they remove the comment.
