### ISSUE TITLE
open /etc/hosts: permission denied

### ISSUE THREAD

**Issue by indirajith** [txn2/txeh#6]
I am using this as Go library and when I try to just run the example provided in the README file, the final 'hosts.Save()'  throws 'open /etc/hosts: permission denied' error. Can you add details to provide root access?

**Comment by jasonmccallister** [comment]
@indirajith this is going to be something the command has to be invoked with. In my project, I have the following, just prior to running `hosts.Save()`:

```go
uid := os.Geteuid()
if uid != 0 {
    return errors.New("sudo permissions are required to edit /etc/hosts file")
}
```

Hope this helps!

**Comment by indirajith** [comment]
@jasonmccallister Thank you very much. Even though it needs the entire program to be run with root privileges, it helped.

**Comment by cjimti** [comment]
@indirajith It is the operating system protecting `/etc/hosts` (as it should). Nothing can be done to circumvent this from the code (which is good).
