### ISSUE TITLE
Show hosts by ip

### ISSUE THREAD

**Issue by jasonmccallister** [txn2/txeh#7]
It would be useful to also show the hosts by an IP, or vice-versa. Would you be open to this feature and pull request? 

Something along the lines of this:

```go
hosts.ListHosts(ip) // returns []string{}
hosts.ListIP(hosts) // returns string
```

**Comment by cjimti** [comment]
@jasonmccallister sounds like a good idea to me. Thank you

**Comment by cjimti** [comment]
Added ListAddressesByHost, ListHostsByCIDR, and ListHostsByIP 1.5.1
