### ISSUE TITLE
New Hosts from string or io.Reader

### ISSUE THREAD

**Issue by kiyonlin** [txn2/txeh#9]
It would be great if supporting to get a new Hosts instance from string or io.Reader 😄

**Comment by cjimti** [comment]
Just released 1.5.2. You can now create a new Hosts instance from a string. Call blankHosts.RenderHostsFile() when you want a new string back after you have made your modifications.

```go
rawData := ""
blankHosts, err := NewHosts(&HostsConfig{
    RawText: &rawData,
})

blankHosts.RenderHostsFile()
```
